/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package delivery;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import models.DeliveryModel;
import models.StockModel;

/**
 *
 * @author Allysha
 */
public class DeliveryForm extends javax.swing.JFrame {

    /**
     * Creates new form DeliveryForm
     */
    
    DeliveryController dc = new DeliveryController();
    
//    private String name;
//    
//    public String getName(){
//        return name;
//    }
//    
//    public void setName(String name){
//        this.name = name;
//    }
    
    public DeliveryForm() {
        initComponents();
        
        this.setLocationRelativeTo(null);
    }
    
    public DeliveryForm(String name){
        initComponents();
        ResultSet rs = null;
        this.setLocationRelativeTo(null);
        setName(name);
        
        rs = dc.getSupplier(); 
        try{
            while (rs.next()){
                comboSupplier.addItem(rs.getString(1));
            }
        } catch (SQLException ex) {
            Logger.getLogger(DeliveryForm.class.getName()).log(Level.SEVERE, null, ex);
        }    
        
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtProductCode = new javax.swing.JTextField();
        txtUnitPrice = new javax.swing.JTextField();
        txtNumberUnits = new javax.swing.JTextField();
        txtUnitMeasure = new javax.swing.JTextField();
        comboSupplier = new javax.swing.JComboBox<>();
        txtEmployee = new javax.swing.JTextField();
        background_addDelivery = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(0, 0));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(153, 255, 255));
        jPanel1.setLayout(null);

        txtProductCode.setFont(new java.awt.Font("Montserrat Light", 1, 14)); // NOI18N
        txtProductCode.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(244, 158, 9), 4));
        jPanel1.add(txtProductCode);
        txtProductCode.setBounds(270, 190, 290, 40);

        txtUnitPrice.setFont(new java.awt.Font("Montserrat Light", 1, 14)); // NOI18N
        txtUnitPrice.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(244, 158, 9), 4));
        jPanel1.add(txtUnitPrice);
        txtUnitPrice.setBounds(270, 250, 290, 40);

        txtNumberUnits.setFont(new java.awt.Font("Montserrat Light", 1, 14)); // NOI18N
        txtNumberUnits.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(244, 158, 9), 4));
        jPanel1.add(txtNumberUnits);
        txtNumberUnits.setBounds(270, 310, 290, 40);

        txtUnitMeasure.setFont(new java.awt.Font("Montserrat Light", 1, 14)); // NOI18N
        txtUnitMeasure.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(244, 158, 9), 4));
        jPanel1.add(txtUnitMeasure);
        txtUnitMeasure.setBounds(270, 380, 290, 40);

        comboSupplier.setFont(new java.awt.Font("Montserrat Light", 1, 14)); // NOI18N
        comboSupplier.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECT SUPPLIER" }));
        jPanel1.add(comboSupplier);
        comboSupplier.setBounds(270, 440, 290, 40);

        txtEmployee.setFont(new java.awt.Font("Montserrat Light", 1, 14)); // NOI18N
        txtEmployee.setText("Username");
        txtEmployee.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(244, 158, 9), 4));
        jPanel1.add(txtEmployee);
        txtEmployee.setBounds(270, 500, 290, 40);

        background_addDelivery.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/FORMADJUSTED-01.png"))); // NOI18N
        jPanel1.add(background_addDelivery);
        background_addDelivery.setBounds(0, 0, 590, 690);

        btnAdd.setText("ADD");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        jPanel1.add(btnAdd);
        btnAdd.setBounds(260, 570, 90, 30);

        btnClear.setText("CLEAR");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        jPanel1.add(btnClear);
        btnClear.setBounds(360, 570, 90, 30);

        btnCancel.setText("CANCEL");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancel);
        btnCancel.setBounds(450, 570, 110, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 590, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 690, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        dc.clear(this);
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        DeliveryPage dp = new DeliveryPage(this.getName());
        
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        StockModel stm = new StockModel();
        DeliveryModel dm = new DeliveryModel();
        
        if(txtProductCode.getText().trim().equals("") || txtUnitPrice.getText().trim().equals("")
            || txtNumberUnits.getText().trim().equals("") || txtUnitMeasure.getText().trim().equals("")
            || comboSupplier.getSelectedItem().equals("") || txtEmployee.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null, "Failed! Please fill up!");
        } 
        else {
             if (JOptionPane.showConfirmDialog(null, "Are you sure you want to add this?", "Confirm Adding",
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            dc.addForm(this);
            System.out.println("Added Delivery Notification");
            
                if (JOptionPane.showConfirmDialog(null, "Do you want to add/update stocks?", "Confirm Adding",
                    JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                    if(stm.determineProdStock(dm.determineProduct(txtProductCode.getText().trim())) != dm.determineProduct(txtProductCode.getText().trim())){
                        dc.addStock(this);
                        System.out.println("ADDED Stock Notification");
                        System.out.println("ProdID is:"+ dm.determineProduct(txtProductCode.getText().trim()));
                        System.out.println("ProdStock is:"+ stm.determineProdStock(dm.determineProduct(txtProductCode.getText().trim())));
                        System.out.println("StockID is:"+ stm.determineStockID(dm.determineProduct(txtProductCode.getText().trim())));
                    }
                    else {
                        dc.updateStock(this);
                        System.out.println("UPDATE Stock Notification");
                    }
                }
            }
            
        }
        
        DeliveryPage dp = new DeliveryPage(this.getName());
        dp.getLblUser().setText("Welcome, "+this.getName());
    }//GEN-LAST:event_btnAddActionPerformed
    
    /**
     * @param args the command line arguments
     */
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeliveryForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeliveryForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeliveryForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeliveryForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeliveryForm().setVisible(true);
            }
        });
    }
    
    public JTextField getTxtProductCode(){
        return txtProductCode;
    }
    
    public JTextField getTxtUnitPrice(){
        return txtUnitPrice;
    }
    
    public JTextField getTxtNumberUnits(){
        return txtNumberUnits;
    }
    
    public JTextField getTxtUnitMeasure(){
        return txtUnitMeasure;
    }
    
    public JComboBox getcomboSupplier(){
        return comboSupplier;
    }
    
    public JTextField getTxtEmployee(){
        return txtEmployee;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background_addDelivery;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnClear;
    private javax.swing.JComboBox<String> comboSupplier;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtEmployee;
    private javax.swing.JTextField txtNumberUnits;
    private javax.swing.JTextField txtProductCode;
    private javax.swing.JTextField txtUnitMeasure;
    private javax.swing.JTextField txtUnitPrice;
    // End of variables declaration//GEN-END:variables

    

}
