/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package productpage;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
/**
 *
 * @author Allysha, Kirby
 */
public class AddProduct extends javax.swing.JFrame {

    /**
     * Creates new form AddProduct
     */
    AddProductController apc = new AddProductController();
    
    /*
    private String name;
    
    public String getName(){
        return name;
    }
    
    public void setName(String name){
        this.name = name;
    }
    */
    
    public AddProduct() {
        initComponents();
        
        this.setLocationRelativeTo(null);
    }
    
    public AddProduct(String name) {
        initComponents();
        ResultSet rs = null;
        this.setLocationRelativeTo(null);
        setName(name);
        
        rs = apc.getCategories();
        try {
            while (rs.next()) {
                comboCategory.addItem(rs.getString(1));
            }
        } catch (SQLException ex) {
            Logger.getLogger(AddProduct.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        txtProductCode = new javax.swing.JTextField();
        txtProductName = new javax.swing.JTextField();
        comboProductType = new javax.swing.JComboBox<>();
        comboCategory = new javax.swing.JComboBox<>();
        txtStandardCost = new javax.swing.JTextField();
        txtMarkupCost = new javax.swing.JTextField();
        background_addProduct = new javax.swing.JLabel();
        AddEmpAddButton = new javax.swing.JButton();
        AddEmpClearButton = new javax.swing.JButton();
        AddEmpCancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(153, 255, 255));
        jPanel2.setLayout(null);

        txtProductCode.setFont(new java.awt.Font("Montserrat Light", 1, 14)); // NOI18N
        txtProductCode.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(244, 158, 9), 2));
        txtProductCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProductCodeActionPerformed(evt);
            }
        });
        jPanel2.add(txtProductCode);
        txtProductCode.setBounds(262, 170, 290, 40);

        txtProductName.setFont(new java.awt.Font("Montserrat Light", 1, 14)); // NOI18N
        txtProductName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(244, 158, 9), 2));
        jPanel2.add(txtProductName);
        txtProductName.setBounds(262, 233, 290, 40);

        comboProductType.setFont(new java.awt.Font("Montserrat Light", 1, 14)); // NOI18N
        comboProductType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECT TYPE", "AGRICULTURE", "NON-AGRICULTURE" }));
        comboProductType.setBorder(null);
        comboProductType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboProductTypeActionPerformed(evt);
            }
        });
        jPanel2.add(comboProductType);
        comboProductType.setBounds(262, 303, 290, 40);

        comboCategory.setFont(new java.awt.Font("Montserrat Light", 1, 14)); // NOI18N
        comboCategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECT CATEGORY" }));
        comboCategory.setBorder(null);
        jPanel2.add(comboCategory);
        comboCategory.setBounds(262, 363, 290, 40);

        txtStandardCost.setFont(new java.awt.Font("Montserrat Light", 1, 14)); // NOI18N
        txtStandardCost.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(244, 158, 9), 2));
        txtStandardCost.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtStandardCostKeyReleased(evt);
            }
        });
        jPanel2.add(txtStandardCost);
        txtStandardCost.setBounds(261, 420, 290, 40);

        txtMarkupCost.setFont(new java.awt.Font("Montserrat Light", 1, 14)); // NOI18N
        txtMarkupCost.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(244, 158, 9), 2));
        jPanel2.add(txtMarkupCost);
        txtMarkupCost.setBounds(261, 480, 290, 40);

        background_addProduct.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/FORMADJUSTED-04.png"))); // NOI18N
        jPanel2.add(background_addProduct);
        background_addProduct.setBounds(0, 0, 640, 690);

        AddEmpAddButton.setText("ADD");
        AddEmpAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddEmpAddButtonActionPerformed(evt);
            }
        });
        jPanel2.add(AddEmpAddButton);
        AddEmpAddButton.setBounds(270, 550, 80, 40);

        AddEmpClearButton.setText("CLEAR");
        AddEmpClearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddEmpClearButtonActionPerformed(evt);
            }
        });
        jPanel2.add(AddEmpClearButton);
        AddEmpClearButton.setBounds(350, 560, 90, 30);

        AddEmpCancelButton.setText("CANCEL");
        AddEmpCancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddEmpCancelButtonActionPerformed(evt);
            }
        });
        jPanel2.add(AddEmpCancelButton);
        AddEmpCancelButton.setBounds(450, 560, 100, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 690, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddEmpCancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddEmpCancelButtonActionPerformed
        this.dispose();
        ProductPage prp = new ProductPage(this.getName());
        prp.getLblUser().setText("Welcome, "+this.getName());
        prp.setVisible(true);
        prp.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }//GEN-LAST:event_AddEmpCancelButtonActionPerformed

    private void AddEmpAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddEmpAddButtonActionPerformed
        if (txtProductCode.getText().trim().equals("") || txtProductName.getText().trim().equals("")
            || comboProductType.getSelectedItem().equals("") || comboCategory.getSelectedItem().equals("")
            || txtStandardCost.getText().trim().equals("") || txtMarkupCost.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Failed! Please fill up!");
        }else {
            if (JOptionPane.showConfirmDialog(null, "Are you sure you want to add this?", "Confirm Adding", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                apc.add(this);
                this.dispose();
                ProductPage prp = new ProductPage(this.getName());
                prp.getLblUser().setText("Welcome, "+this.getName());
                prp.setVisible(true);
                prp.setExtendedState(JFrame.MAXIMIZED_BOTH);
            }
        }
        
    }//GEN-LAST:event_AddEmpAddButtonActionPerformed

    private void AddEmpClearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddEmpClearButtonActionPerformed
        apc.clear(this);
    }//GEN-LAST:event_AddEmpClearButtonActionPerformed

    private void txtStandardCostKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtStandardCostKeyReleased


    }//GEN-LAST:event_txtStandardCostKeyReleased

    private void txtProductCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProductCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProductCodeActionPerformed

    private void comboProductTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboProductTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboProductTypeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddProduct().setVisible(true);
            }
        });
    }
    
    
    //Getters
    public JTextField getTxtProductCode(){
        return txtProductCode;
    }
    
    public JTextField getTxtProductName() {
        return txtProductName;
    }
    
    public JComboBox getcomboProductType() {
        return comboProductType;
    }

    public JComboBox getcomboCategory() {
        return comboCategory;
    }
    
    public JTextField getTxtStandardCost() {
        return txtStandardCost;
    }
    
    public JTextField getTxtMarkupCost() {
        return txtMarkupCost;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddEmpAddButton;
    private javax.swing.JButton AddEmpCancelButton;
    private javax.swing.JButton AddEmpClearButton;
    private javax.swing.JLabel background_addProduct;
    private javax.swing.JComboBox<String> comboCategory;
    private javax.swing.JComboBox<String> comboProductType;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtMarkupCost;
    private javax.swing.JTextField txtProductCode;
    private javax.swing.JTextField txtProductName;
    private javax.swing.JTextField txtStandardCost;
    // End of variables declaration//GEN-END:variables

}
