/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package productpage;

import javax.swing.JLabel; 
import javax.swing.JOptionPane;
import javax.swing.JTable; 
import login.Login;
import adminpage.AdminPage; 
import java.sql.ResultSet;
import java.util.regex.PatternSyntaxException;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import net.proteanit.sql.DbUtils; 
import models.ProductModel;

/**
 *
 * @author Allysha, Kirby
 */
public class ProductPage extends javax.swing.JFrame {

    /**
     * Creates new form ProductPage
     */
    
    public ProductPage(){
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    public ProductPage (String name){
        initComponents();
        
        this.setLocationRelativeTo(null);
        setName(name);
        
        ProductModel pm = new ProductModel(); //links the product model           
        ResultSet rs = pm.viewAll();          //calls the query from the product model to display the products
        String val = pm.determineBranch(name);  
        
        if(val.compareTo("1")==0){
            comboBranch.setSelectedIndex(0);
            rs = pm.viewAll2("1");
        }else{
            comboBranch.setSelectedIndex(1);
            rs = pm.viewAll2("2");
        }
        
        tblProduct.setModel(DbUtils.resultSetToTableModel(rs));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblUser = new javax.swing.JLabel();
        searchProduct = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblProduct = new javax.swing.JTable();
        comboBranch = new javax.swing.JComboBox<>();
        background_product = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 255, 255));
        jPanel1.setLayout(null);

        lblUser.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblUser.setText("jLabel3");
        jPanel1.add(lblUser);
        lblUser.setBounds(1070, 30, 180, 30);

        searchProduct.setBackground(new java.awt.Color(241, 242, 242));
        searchProduct.setFont(new java.awt.Font("Montserrat Light", 1, 14)); // NOI18N
        searchProduct.setBorder(null);
        searchProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchProductActionPerformed(evt);
            }
        });
        searchProduct.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchProductKeyReleased(evt);
            }
        });
        jPanel1.add(searchProduct);
        searchProduct.setBounds(80, 240, 320, 30);

        jPanel2.setBackground(new java.awt.Color(244, 158, 9));

        jScrollPane2.setBorder(null);
        jScrollPane2.setMaximumSize(new java.awt.Dimension(32700, 32767));
        jScrollPane2.setMinimumSize(new java.awt.Dimension(0, 0));

        tblProduct.setFont(new java.awt.Font("Montserrat Light", 0, 14)); // NOI18N
        tblProduct.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblProduct.setGridColor(new java.awt.Color(255, 255, 255));
        tblProduct.setRowHeight(30);
        tblProduct.setRowMargin(3);
        tblProduct.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(tblProduct);
        if (tblProduct.getColumnModel().getColumnCount() > 0) {
            tblProduct.getColumnModel().getColumn(0).setResizable(false);
            tblProduct.getColumnModel().getColumn(0).setPreferredWidth(50);
            tblProduct.getColumnModel().getColumn(1).setResizable(false);
            tblProduct.getColumnModel().getColumn(2).setResizable(false);
            tblProduct.getColumnModel().getColumn(3).setResizable(false);
        }

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1290, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(30, 290, 1310, 410);

        comboBranch.setFont(new java.awt.Font("Montserrat Light", 1, 14)); // NOI18N
        comboBranch.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cebu Branch", "Leyte Branch" }));
        comboBranch.setBorder(null);
        comboBranch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBranchActionPerformed(evt);
            }
        });
        jPanel1.add(comboBranch);
        comboBranch.setBounds(1050, 180, 290, 40);

        background_product.setBackground(new java.awt.Color(241, 242, 242));
        background_product.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        background_product.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/PRODUCTADJUSTED-01.png"))); // NOI18N
        jPanel1.add(background_product);
        background_product.setBounds(0, 0, 1360, 720);

        btnBack.setText("BACK");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel1.add(btnBack);
        btnBack.setBounds(10, 10, 110, 70);

        btnAdd.setText("ADD");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        jPanel1.add(btnAdd);
        btnAdd.setBounds(930, 240, 90, 50);

        btnUpdate.setText("UPDATE");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        jPanel1.add(btnUpdate);
        btnUpdate.setBounds(1030, 240, 130, 50);

        btnDelete.setText("DELETE");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        jPanel1.add(btnDelete);
        btnDelete.setBounds(1170, 240, 170, 50);

        btnLogout.setText("jButton1");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        jPanel1.add(btnLogout);
        btnLogout.setBounds(1260, 10, 90, 80);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1360, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        //delete button to delete a product
        if (tblProduct.getSelectedRow() != -1) {
            String productNumber;
            ProductPageController ppc = new ProductPageController(); //links productpagecontroller
            productNumber = tblProduct.getValueAt(tblProduct.getSelectedRow(), 0).toString();
            ppc.deleteProduct(productNumber); //calls the delete function from the controller
        } else {
            JOptionPane.showMessageDialog(null, "Please select an item first!");
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        //goes back to the adminpage
        AdminPage ap = new AdminPage(this.getName());
        ap.getLblUser().setText("Welcome "+this.getName());
        ap.setVisible(true);
       
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        //links to an add product form. the admin will fill up there.
        AddProduct ap = new AddProduct(this.getName());
        ap.setVisible(true);
    }//GEN-LAST:event_btnAddActionPerformed

    private void searchProductKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchProductKeyReleased
       DefaultTableModel model = (DefaultTableModel) tblProduct.getModel();
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel> (model);
        tblProduct.setRowSorter(tr);
        try {
            tr.setRowFilter(RowFilter.regexFilter("(?i)"+searchProduct.getText()));
        } catch (PatternSyntaxException e) {
            
        }
    }//GEN-LAST:event_searchProductKeyReleased

    private void comboBranchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBranchActionPerformed
        ProductModel pm = new ProductModel();
        ResultSet rs = null;
        
        if(comboBranch.getSelectedItem().toString().compareTo("Cebu Branch")==0){
            rs = pm.viewAll2("1");
        }else{
            rs = pm.viewAll2("2");
        }
        
        tblProduct.setModel(DbUtils.resultSetToTableModel(rs)); 


        DefaultTableModel model = (DefaultTableModel) tblProduct.getModel();
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel> (model);
        tblProduct.setRowSorter(tr);
        
        try {
            tr.setRowFilter(RowFilter.regexFilter("(?i)"+searchProduct.getText()));      
        } catch (PatternSyntaxException e) {
            
        }
    }//GEN-LAST:event_comboBranchActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        if (tblProduct.getSelectedRow() != -1) {
            UpdateProduct up = new UpdateProduct(this.getName(), tblProduct.getValueAt(tblProduct.getSelectedRow(), 0).toString(), tblProduct.getValueAt(tblProduct.getSelectedRow(), 1).toString(), tblProduct.getValueAt(tblProduct.getSelectedRow(), 2).toString(), tblProduct.getValueAt(tblProduct.getSelectedRow(), 3).toString(), tblProduct.getValueAt(tblProduct.getSelectedRow(), 4).toString(), tblProduct.getValueAt(tblProduct.getSelectedRow(), 5).toString());
            up.setVisible(true);    
        } else {
            JOptionPane.showMessageDialog(null, "Please select an item first!");
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void searchProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchProductActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchProductActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        Login l = new Login();
        l.setVisible(true);

        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_btnLogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProductPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProductPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProductPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProductPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProductPage().setVisible(true);
            }
        });
    }

    
    public JTable getTblProduct(){  
        return tblProduct;
    }
    
    public JLabel getLblUser() {
        return lblUser;
    }
    
    
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background_product;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> comboBranch;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblUser;
    private javax.swing.JTextField searchProduct;
    private javax.swing.JTable tblProduct;
    // End of variables declaration//GEN-END:variables

}
