/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package productpage;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
/**
 *
 * @author Client
 */
public class UpdateProduct extends javax.swing.JFrame {

    /**
     * Creates new form UpdateProduct
     */
    UpdateProductController updc = new UpdateProductController();
    
    private String name;
    
    public String getName(){
        return name;
    }
    
    public void setName(String name){
        this.name = name;
    }
    
    public UpdateProduct() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        //DATA YOU CAN ONLY UPDATE
        txtProductName.setText("");
        comboProductType.setSelectedIndex(0);
        comboCategory.setSelectedIndex(0);
        txtStandardCost.setText("");
        txtMarkupCost.setText(""); 
    }
    
    public UpdateProduct(String name, String productCode, String productName, String productCategory, String productType, String standardCost, String markupCost) {
        initComponents();
        ResultSet rs = null; ///pm.update();
        int ndx, val;
        val = 0;
        this.setLocationRelativeTo(null);
        setName(name);
        
        txtItemCode.setText(productCode);
        txtProductName.setText(productName);
        txtStandardCost.setText(standardCost);
        txtMarkupCost.setText(markupCost);
        
        rs = updc.getCategories();
        if(productType.compareToIgnoreCase("AGRICULTURAL")==0){
            comboProductType.setSelectedIndex(1);
        }else{
            comboProductType.setSelectedIndex(2);
        }
        try {
            for(ndx = 0; rs.next(); ndx++) {
                comboCategory.addItem(rs.getString(1));
                if(productCategory.compareToIgnoreCase(rs.getString(1))==0){
                    val = ndx;
                }
            }
            comboCategory.setSelectedIndex(val+1);
        } catch (SQLException ex) {
            Logger.getLogger(AddProduct.class.getName()).log(Level.SEVERE, null, ex);
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        txtProductName = new javax.swing.JTextField();
        comboProductType = new javax.swing.JComboBox<>();
        comboCategory = new javax.swing.JComboBox<>();
        txtItemCode = new javax.swing.JTextField();
        txtStandardCost = new javax.swing.JTextField();
        txtMarkupCost = new javax.swing.JTextField();
        background_updateProduct = new javax.swing.JLabel();
        UpdateProdClear = new javax.swing.JButton();
        UpdateProdCancel = new javax.swing.JButton();
        UpdateProdUpdate = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(153, 255, 255));
        jPanel2.setLayout(null);

        txtProductName.setFont(new java.awt.Font("Montserrat Light", 1, 14)); // NOI18N
        txtProductName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(244, 158, 9), 2));
        jPanel2.add(txtProductName);
        txtProductName.setBounds(270, 243, 280, 40);

        comboProductType.setFont(new java.awt.Font("Montserrat Light", 1, 14)); // NOI18N
        comboProductType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECT TYPE", "AGRICULTURE", "NON-AGRICULTURE" }));
        comboProductType.setBorder(null);
        comboProductType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboProductTypeActionPerformed(evt);
            }
        });
        jPanel2.add(comboProductType);
        comboProductType.setBounds(270, 300, 280, 40);

        comboCategory.setFont(new java.awt.Font("Montserrat Light", 1, 14)); // NOI18N
        comboCategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECT CATEGORY" }));
        comboCategory.setBorder(null);
        comboCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboCategoryActionPerformed(evt);
            }
        });
        jPanel2.add(comboCategory);
        comboCategory.setBounds(270, 360, 280, 40);

        txtItemCode.setFont(new java.awt.Font("Montserrat Light", 1, 14)); // NOI18N
        txtItemCode.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(244, 158, 9), 2));
        jPanel2.add(txtItemCode);
        txtItemCode.setBounds(270, 183, 280, 40);

        txtStandardCost.setFont(new java.awt.Font("Montserrat Light", 1, 14)); // NOI18N
        txtStandardCost.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(244, 158, 9), 2));
        jPanel2.add(txtStandardCost);
        txtStandardCost.setBounds(270, 420, 280, 40);

        txtMarkupCost.setFont(new java.awt.Font("Montserrat Light", 1, 14)); // NOI18N
        txtMarkupCost.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(244, 158, 9), 2));
        jPanel2.add(txtMarkupCost);
        txtMarkupCost.setBounds(270, 490, 280, 40);

        background_updateProduct.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/FORMADJUSTED-05.png"))); // NOI18N
        jPanel2.add(background_updateProduct);
        background_updateProduct.setBounds(0, 0, 600, 700);

        UpdateProdClear.setText("CLEAR");
        UpdateProdClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateProdClearActionPerformed(evt);
            }
        });
        jPanel2.add(UpdateProdClear);
        UpdateProdClear.setBounds(370, 560, 80, 30);

        UpdateProdCancel.setText("CANCEL");
        UpdateProdCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateProdCancelActionPerformed(evt);
            }
        });
        jPanel2.add(UpdateProdCancel);
        UpdateProdCancel.setBounds(460, 560, 100, 30);

        UpdateProdUpdate.setText("UPDATE");
        UpdateProdUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateProdUpdateActionPerformed(evt);
            }
        });
        jPanel2.add(UpdateProdUpdate);
        UpdateProdUpdate.setBounds(260, 560, 100, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboCategoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboCategoryActionPerformed

    private void UpdateProdClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateProdClearActionPerformed
        updc.clear(this);
    }//GEN-LAST:event_UpdateProdClearActionPerformed

    private void UpdateProdUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateProdUpdateActionPerformed
       if (txtItemCode.getText().trim().equals("") || txtProductName.getText().trim().equals("")
            || comboProductType.getSelectedItem().equals("") || comboCategory.getSelectedItem().equals("")
            || txtStandardCost.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Failed! Please fill up!");
        }else {
            if (JOptionPane.showConfirmDialog(null, "Are you sure you want to update this?", "Confirm Update",
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            updc.update(this);
            this.dispose();
            ProductPage prp = new ProductPage(this.getName());
            prp.getLblUser().setText("Welcome, "+this.getName());
            prp.setVisible(true);
            prp.setExtendedState(JFrame.MAXIMIZED_BOTH);    
            }
        }
    }//GEN-LAST:event_UpdateProdUpdateActionPerformed

    private void UpdateProdCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateProdCancelActionPerformed
            this.dispose();
            ProductPage prp = new ProductPage(this.getName());
            prp.getLblUser().setText("Welcome, "+this.getName());
            prp.setVisible(true);
            prp.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }//GEN-LAST:event_UpdateProdCancelActionPerformed

    private void comboProductTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboProductTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboProductTypeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               new UpdateProduct().setVisible(true);
            }
        });
    }
    
    public JTextField getTxtItemCode(){
        return txtItemCode;
    }
    
    public JTextField getTxtProductName() {
        return txtProductName;
    }

    public JComboBox getcomboCategory() {
        return comboProductType;
    }

    public JComboBox getcomboProductType() {
        return comboCategory;
    }
    
    public JTextField getTxtStandardCost(){
        return txtStandardCost;
    }
    
    public JTextField getTxtMarkupCost(){
        return txtMarkupCost;
    }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton UpdateProdCancel;
    private javax.swing.JButton UpdateProdClear;
    private javax.swing.JButton UpdateProdUpdate;
    private javax.swing.JLabel background_updateProduct;
    private javax.swing.JComboBox<String> comboCategory;
    private javax.swing.JComboBox<String> comboProductType;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtItemCode;
    private javax.swing.JTextField txtMarkupCost;
    private javax.swing.JTextField txtProductName;
    private javax.swing.JTextField txtStandardCost;
    // End of variables declaration//GEN-END:variables
}
