/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package peoplepage;

import javax.swing.JLabel;
import javax.swing.JOptionPane;
import login.Login;
import adminpage.AdminPage;
import java.sql.ResultSet;
import java.util.regex.PatternSyntaxException;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import models.SupplierModel;
import models.EmployeeModel;
import net.proteanit.sql.DbUtils;

//
/**
 *
 * @author Allysha
 */
public class PeoplePage extends javax.swing.JFrame {

    /**
     * Creates new form PeoplePage
     */
    
    //PeoplePageController ppl = new PeoplePageController();
    
    
    private String name;
    
    public String getName(){
        return name;
    }
    
    public void setName(String name){
        this.name = name;
    }
    
    public PeoplePage() {
        initComponents();
        
        this.setLocationRelativeTo(null);
    }
    
    public PeoplePage(String name){
        initComponents();
        
        this.setLocationRelativeTo(null);
        setName(name);
        
        EmployeeModel em = new EmployeeModel();
        SupplierModel sm = new SupplierModel();
        ResultSet rs = em.viewAll(); //null;
        ResultSet rs2 = sm.viewAll();
        
        String val = em.determineBranch(name);
        if(val.compareTo("1")==0){
            comboBranch.setSelectedIndex(0);
            rs = em.viewLeyte("1");
        }else{
            comboBranch.setSelectedIndex(1);
            rs = em.viewLeyte("2");
        }
        
        tblEmp.setModel(DbUtils.resultSetToTableModel(rs));
        tblSupplier.setModel(DbUtils.resultSetToTableModel(rs2));
    }
    

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblUser = new javax.swing.JLabel();
        jTabbedPane = new javax.swing.JTabbedPane();
        tab_employee = new javax.swing.JPanel();
        searchEmployee = new javax.swing.JTextField();
        comboBranch = new javax.swing.JComboBox<>();
        jScrollPane_EMP = new javax.swing.JScrollPane();
        tblEmp = new javax.swing.JTable();
        background_employee = new javax.swing.JLabel();
        btnBack1 = new javax.swing.JButton();
        btnLogout1 = new javax.swing.JButton();
        AddEmp = new javax.swing.JButton();
        UpdateEmp = new javax.swing.JButton();
        DeleteEmp = new javax.swing.JButton();
        jButton1Employee = new javax.swing.JButton();
        jButton1Supplier = new javax.swing.JButton();
        tab_supplier = new javax.swing.JPanel();
        searchSupplier = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblSupplier = new javax.swing.JTable();
        background_supplier = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        AddSupplier = new javax.swing.JButton();
        UpdateSupplier = new javax.swing.JButton();
        DeleteSupplier = new javax.swing.JButton();
        jButton2Employee = new javax.swing.JButton();
        jButton2Supplier = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(241, 242, 242));

        lblUser.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblUser.setText("jLabel1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(1054, Short.MAX_VALUE)
                .addComponent(lblUser, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(106, 106, 106))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 8, Short.MAX_VALUE)
                .addComponent(lblUser))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1360, 30);

        tab_employee.setLayout(null);

        searchEmployee.setBackground(new java.awt.Color(241, 242, 242));
        searchEmployee.setFont(new java.awt.Font("Montserrat Light", 1, 14)); // NOI18N
        searchEmployee.setBorder(null);
        searchEmployee.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchEmployeeKeyReleased(evt);
            }
        });
        tab_employee.add(searchEmployee);
        searchEmployee.setBounds(90, 270, 310, 20);

        comboBranch.setFont(new java.awt.Font("Montserrat Light", 1, 18)); // NOI18N
        comboBranch.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cebu Branch", "Leyte Branch" }));
        comboBranch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBranchActionPerformed(evt);
            }
        });
        tab_employee.add(comboBranch);
        comboBranch.setBounds(1020, 180, 300, 40);

        tblEmp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblEmp.setRowHeight(25);
        tblEmp.getTableHeader().setReorderingAllowed(false);
        jScrollPane_EMP.setViewportView(tblEmp);
        tblEmp.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        tab_employee.add(jScrollPane_EMP);
        jScrollPane_EMP.setBounds(40, 310, 1290, 360);

        background_employee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/EMPLOYEESADJUSTED-04.png"))); // NOI18N
        tab_employee.add(background_employee);
        background_employee.setBounds(0, 0, 1360, 710);

        btnBack1.setText("BACK");
        btnBack1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack1ActionPerformed(evt);
            }
        });
        tab_employee.add(btnBack1);
        btnBack1.setBounds(20, 10, 110, 70);

        btnLogout1.setText("LOGOUT");
        btnLogout1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogout1ActionPerformed(evt);
            }
        });
        tab_employee.add(btnLogout1);
        btnLogout1.setBounds(1260, 10, 80, 70);

        AddEmp.setText("ADD");
        AddEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddEmpActionPerformed(evt);
            }
        });
        tab_employee.add(AddEmp);
        AddEmp.setBounds(920, 240, 90, 30);

        UpdateEmp.setText("UPDATE");
        UpdateEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateEmpActionPerformed(evt);
            }
        });
        tab_employee.add(UpdateEmp);
        UpdateEmp.setBounds(1020, 240, 130, 30);

        DeleteEmp.setText("DELETE");
        DeleteEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteEmpActionPerformed(evt);
            }
        });
        tab_employee.add(DeleteEmp);
        DeleteEmp.setBounds(1160, 240, 160, 30);

        jButton1Employee.setText("employee");
        jButton1Employee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1EmployeeActionPerformed(evt);
            }
        });
        tab_employee.add(jButton1Employee);
        jButton1Employee.setBounds(40, 190, 300, 60);

        jButton1Supplier.setText("supplier");
        jButton1Supplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1SupplierActionPerformed(evt);
            }
        });
        tab_employee.add(jButton1Supplier);
        jButton1Supplier.setBounds(360, 190, 320, 60);

        jTabbedPane.addTab("EMPLOYEE", tab_employee);

        tab_supplier.setLayout(null);

        searchSupplier.setBackground(new java.awt.Color(241, 242, 242));
        searchSupplier.setFont(new java.awt.Font("Montserrat Light", 1, 14)); // NOI18N
        searchSupplier.setBorder(null);
        searchSupplier.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchSupplierKeyReleased(evt);
            }
        });
        tab_supplier.add(searchSupplier);
        searchSupplier.setBounds(90, 270, 310, 20);

        tblSupplier.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tblSupplier);

        tab_supplier.add(jScrollPane2);
        jScrollPane2.setBounds(40, 310, 1290, 360);

        background_supplier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/SUPPLIERSADJUSTED-05.png"))); // NOI18N
        tab_supplier.add(background_supplier);
        background_supplier.setBounds(0, -10, 1360, 730);

        btnBack.setText("BACK");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        tab_supplier.add(btnBack);
        btnBack.setBounds(20, 20, 110, 70);

        btnLogout.setText("LOGOUT");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        tab_supplier.add(btnLogout);
        btnLogout.setBounds(1250, 10, 90, 80);

        AddSupplier.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        AddSupplier.setText("ADD");
        AddSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddSupplierActionPerformed(evt);
            }
        });
        tab_supplier.add(AddSupplier);
        AddSupplier.setBounds(910, 240, 100, 50);

        UpdateSupplier.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        UpdateSupplier.setText("UPDATE");
        UpdateSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateSupplierActionPerformed(evt);
            }
        });
        tab_supplier.add(UpdateSupplier);
        UpdateSupplier.setBounds(1020, 240, 130, 50);

        DeleteSupplier.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        DeleteSupplier.setText("DELETE");
        DeleteSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteSupplierActionPerformed(evt);
            }
        });
        tab_supplier.add(DeleteSupplier);
        DeleteSupplier.setBounds(1160, 240, 170, 50);

        jButton2Employee.setText("employee");
        jButton2Employee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2EmployeeActionPerformed(evt);
            }
        });
        tab_supplier.add(jButton2Employee);
        jButton2Employee.setBounds(40, 200, 300, 60);

        jButton2Supplier.setText("supplier");
        jButton2Supplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2SupplierActionPerformed(evt);
            }
        });
        tab_supplier.add(jButton2Supplier);
        jButton2Supplier.setBounds(360, 200, 320, 60);

        jTabbedPane.addTab("SUPPLIER", tab_supplier);

        getContentPane().add(jTabbedPane);
        jTabbedPane.setBounds(0, 0, 1360, 780);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        Login l = new Login();
        l.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        AdminPage ap = new AdminPage(this.getName());
        ap.getLblUser().setText("Welcome, "+this.getName());
        ap.setVisible(true);

        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void searchSupplierKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchSupplierKeyReleased
        DefaultTableModel model = (DefaultTableModel) tblSupplier.getModel();
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel> (model);
        tblSupplier.setRowSorter(tr);
        try {
            tr.setRowFilter(RowFilter.regexFilter("(?i)"+searchSupplier.getText()));
        } catch (PatternSyntaxException e) {

        }
    }//GEN-LAST:event_searchSupplierKeyReleased

    private void AddSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddSupplierActionPerformed
        this.dispose();
        AddSupplier as = new AddSupplier(this.getName());
        as.setVisible(true);
    }//GEN-LAST:event_AddSupplierActionPerformed

    private void UpdateSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateSupplierActionPerformed
        if (tblSupplier.getSelectedRow() != -1) {
            UpdateSupplier us = new UpdateSupplier(this.getName(), Integer.parseInt(tblSupplier.getValueAt(tblSupplier.getSelectedRow(), 0).toString()), tblSupplier.getValueAt(tblSupplier.getSelectedRow(), 1).toString(), tblSupplier.getValueAt(tblSupplier.getSelectedRow(), 2).toString(), tblSupplier.getValueAt(tblSupplier.getSelectedRow(), 3).toString(), tblSupplier.getValueAt(tblSupplier.getSelectedRow(), 4).toString(), tblSupplier.getValueAt(tblSupplier.getSelectedRow(), 5).toString());
            us.setVisible(true);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(null, "Please select an supplier first!");
        }
    }//GEN-LAST:event_UpdateSupplierActionPerformed

    private void DeleteSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteSupplierActionPerformed
        if (tblSupplier.getSelectedRow() != -1) {
            int supplierNumber;
            PeoplePageController peop = new PeoplePageController();
            supplierNumber = Integer.parseInt(tblSupplier.getModel().getValueAt(tblSupplier.getSelectedRow(), 0).toString());
            peop.deleteSupplier(supplierNumber);

            SupplierModel sm = new SupplierModel();
            ResultSet rs = sm.viewAll();
            tblSupplier.setModel(DbUtils.resultSetToTableModel(rs));
        }
        else {
            JOptionPane.showMessageDialog(null, "Please select a supplier first!");
        }

    }//GEN-LAST:event_DeleteSupplierActionPerformed

    private void comboBranchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBranchActionPerformed
        EmployeeModel em = new EmployeeModel();
        ResultSet rs = null;

        if(comboBranch.getSelectedItem().toString().compareTo("Cebu Branch")==0){
            rs = em.viewLeyte("1");
        }else{
            rs = em.viewLeyte("2");
        }

        tblEmp.setModel(DbUtils.resultSetToTableModel(rs));

        DefaultTableModel model = (DefaultTableModel) tblEmp.getModel();
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel> (model);
        tblEmp.setRowSorter(tr);
        try {
            tr.setRowFilter(RowFilter.regexFilter("(?i)"+searchEmployee.getText()));
        } catch (PatternSyntaxException e) {

        }
    }//GEN-LAST:event_comboBranchActionPerformed

    private void DeleteEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteEmpActionPerformed
        if (tblEmp.getSelectedRow() != -1) {
            int empNumber;
            PeoplePageController peop = new PeoplePageController();
            empNumber = Integer.parseInt(tblEmp.getModel().getValueAt(tblEmp.getSelectedRow(), 0).toString());
            peop.deleteEmp(empNumber);

            EmployeeModel em = new EmployeeModel();
            ResultSet rs = null;
            String val = em.determineBranch(name);

            if(val.compareTo("1")==0){
                comboBranch.setSelectedIndex(0);
                rs = em.viewLeyte("1");
            }else{
                comboBranch.setSelectedIndex(1);
                rs = em.viewLeyte("2");
            }

            tblEmp.setModel(DbUtils.resultSetToTableModel(rs));

        }
        else {
            JOptionPane.showMessageDialog(null, "Please select an employee first!");
        }
    }//GEN-LAST:event_DeleteEmpActionPerformed

    private void UpdateEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateEmpActionPerformed
        if (tblEmp.getSelectedRow() != -1) {
            UpdateEmp ue = new UpdateEmp(this.getName(), Integer.parseInt(tblEmp.getValueAt(tblEmp.getSelectedRow(), 0).toString()), tblEmp.getValueAt(tblEmp.getSelectedRow(), 1).toString(), tblEmp.getValueAt(tblEmp.getSelectedRow(), 2).toString(), tblEmp.getValueAt(tblEmp.getSelectedRow(), 3).toString(), tblEmp.getValueAt(tblEmp.getSelectedRow(), 4).toString(), tblEmp.getValueAt(tblEmp.getSelectedRow(), 5).toString(), tblEmp.getValueAt(tblEmp.getSelectedRow(), 6).toString(),  tblEmp.getValueAt(tblEmp.getSelectedRow(), 7).toString());
            ue.setVisible(true);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(null, "Please select an employee first!");
        }
    }//GEN-LAST:event_UpdateEmpActionPerformed

    private void AddEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddEmpActionPerformed
        this.dispose();
        AddEmp ae = new AddEmp(this.getName());
        ae.setVisible(true);
    }//GEN-LAST:event_AddEmpActionPerformed

    private void searchEmployeeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchEmployeeKeyReleased
        DefaultTableModel model = (DefaultTableModel) tblEmp.getModel();
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel> (model);
        tblEmp.setRowSorter(tr);
        try {
            tr.setRowFilter(RowFilter.regexFilter("(?i)"+searchEmployee.getText()));
        } catch (PatternSyntaxException e) {

        }
    }//GEN-LAST:event_searchEmployeeKeyReleased

    private void jButton1SupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1SupplierActionPerformed
    jTabbedPane.setSelectedIndex(1);        
    }//GEN-LAST:event_jButton1SupplierActionPerformed

    private void jButton1EmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1EmployeeActionPerformed
        jTabbedPane.setSelectedIndex(0);
    }//GEN-LAST:event_jButton1EmployeeActionPerformed

    private void jButton2SupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2SupplierActionPerformed
        jTabbedPane.setSelectedIndex(1);     
    }//GEN-LAST:event_jButton2SupplierActionPerformed

    private void jButton2EmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2EmployeeActionPerformed
        jTabbedPane.setSelectedIndex(0);
    }//GEN-LAST:event_jButton2EmployeeActionPerformed

    private void btnBack1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack1ActionPerformed
        AdminPage ap = new AdminPage(this.getName());
        ap.getLblUser().setText("Welcome "+this.getName());
        ap.setVisible(true);

        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_btnBack1ActionPerformed

    private void btnLogout1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogout1ActionPerformed
        Login l = new Login();
        l.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_btnLogout1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PeoplePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PeoplePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PeoplePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PeoplePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PeoplePage().setVisible(true);
            }
        });
    }
    
    public JLabel getLblUser() {
        return lblUser;
    }
    
    
    public JTextField getTxtSearch() {
        return searchEmployee;
    }
    
    public JTable getTblEmp() {
        return tblEmp;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddEmp;
    private javax.swing.JButton AddSupplier;
    private javax.swing.JButton DeleteEmp;
    private javax.swing.JButton DeleteSupplier;
    private javax.swing.JButton UpdateEmp;
    private javax.swing.JButton UpdateSupplier;
    private javax.swing.JLabel background_employee;
    private javax.swing.JLabel background_supplier;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnBack1;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnLogout1;
    private javax.swing.JComboBox<String> comboBranch;
    private javax.swing.JButton jButton1Employee;
    private javax.swing.JButton jButton1Supplier;
    private javax.swing.JButton jButton2Employee;
    private javax.swing.JButton jButton2Supplier;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane_EMP;
    private javax.swing.JTabbedPane jTabbedPane;
    private javax.swing.JLabel lblUser;
    private javax.swing.JTextField searchEmployee;
    private javax.swing.JTextField searchSupplier;
    private javax.swing.JPanel tab_employee;
    private javax.swing.JPanel tab_supplier;
    private javax.swing.JTable tblEmp;
    private javax.swing.JTable tblSupplier;
    // End of variables declaration//GEN-END:variables



}
