/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package peoplepage;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
import peoplepage.PeoplePage;
import models.EmployeeModel;

/**
 *
 * @author allysh@
 */
public class UpdateEmp extends javax.swing.JFrame {
    /**
     * Creates new form AddEmp
     */
    UpdateEmpController uec = new UpdateEmpController();
    
    private String name;
    private int empId;
    
    public String getName(){
        return name;
    }
    
    public void setName(String name){
        this.name = name;
    }
    
    public int getEmpId(){
        return empId;
    }
    
    public void setEmpId(int empId){
        this.empId = empId;
    }
    
    public UpdateEmp() {
        initComponents();
        this.setLocationRelativeTo(null);
        
            //DATA U CAN ONLY UPDATE
            txtFirstname.setText("");
            txtLastname.setText("");
            txtUsername.setText("");
            txtPassword.setText("");
            txtConfirm.setText("");
            txtEmail.setText("");
            txtContactNumber.setText("");
            txtAddress.setText("");
            comboRole.setSelectedIndex(0);
    }
    
    public UpdateEmp(String name, int empId, String firstname, String lastname, String username, String email, String contact, String address, String role) {
        initComponents();
        EmployeeModel em = new EmployeeModel();
        ResultSet rs = null; //em.update;
        int ndx, val;
        val = 0;
        this.setLocationRelativeTo(null);
        setName(name);
        String password = "";
        String confirm = "";
        setEmpId(empId);
        System.out.println("Employee ID:"+empId);
        
        txtFirstname.setText(firstname);
        txtLastname.setText(lastname);
        txtUsername.setText(username);
        txtPassword.setText(password);
        txtConfirm.setText(confirm);
        txtEmail.setText(email);
        txtContactNumber.setText(contact);
        txtAddress.setText(address);
        
        rs = uec.getRole();
        try{
            for (ndx = 0; rs.next(); ndx++){
                comboRole.addItem(rs.getString(1));  
                if(role.compareToIgnoreCase(rs.getString(1))==0){
                    val = ndx;
                }
            }
        } catch (SQLException ex){
             Logger.getLogger(UpdateEmp.class.getName()).log(Level.SEVERE, null, ex);
        }       
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        txtFirstname = new javax.swing.JTextField();
        txtLastname = new javax.swing.JTextField();
        txtUsername = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        txtConfirm = new javax.swing.JPasswordField();
        txtEmail = new javax.swing.JTextField();
        txtContactNumber = new javax.swing.JTextField();
        txtAddress = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        comboRole = new javax.swing.JComboBox<>();
        background_updateEmployee = new javax.swing.JLabel();
        btnUpdate = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add New User");
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(153, 255, 255));
        jPanel2.setLayout(null);

        txtFirstname.setFont(new java.awt.Font("Montserrat Light", 1, 14)); // NOI18N
        txtFirstname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(244, 158, 9), 2));
        jPanel2.add(txtFirstname);
        txtFirstname.setBounds(280, 150, 280, 40);

        txtLastname.setFont(new java.awt.Font("Montserrat Light", 1, 14)); // NOI18N
        txtLastname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(244, 158, 9), 2));
        txtLastname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLastnameActionPerformed(evt);
            }
        });
        jPanel2.add(txtLastname);
        txtLastname.setBounds(280, 200, 280, 40);

        txtUsername.setFont(new java.awt.Font("Montserrat Light", 1, 14)); // NOI18N
        txtUsername.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(244, 158, 9), 2));
        jPanel2.add(txtUsername);
        txtUsername.setBounds(280, 250, 280, 40);

        txtPassword.setFont(new java.awt.Font("Montserrat Light", 1, 14)); // NOI18N
        txtPassword.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(244, 158, 9), 2));
        jPanel2.add(txtPassword);
        txtPassword.setBounds(280, 300, 280, 40);

        txtConfirm.setFont(new java.awt.Font("Montserrat Light", 1, 14)); // NOI18N
        txtConfirm.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(244, 158, 9), 2));
        txtConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtConfirmActionPerformed(evt);
            }
        });
        jPanel2.add(txtConfirm);
        txtConfirm.setBounds(279, 350, 280, 40);

        txtEmail.setFont(new java.awt.Font("Montserrat Light", 1, 14)); // NOI18N
        txtEmail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(244, 158, 9), 2));
        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });
        jPanel2.add(txtEmail);
        txtEmail.setBounds(280, 400, 280, 40);

        txtContactNumber.setFont(new java.awt.Font("Montserrat Light", 1, 14)); // NOI18N
        txtContactNumber.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(244, 158, 9), 2));
        txtContactNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContactNumberActionPerformed(evt);
            }
        });
        jPanel2.add(txtContactNumber);
        txtContactNumber.setBounds(280, 450, 280, 40);

        txtAddress.setFont(new java.awt.Font("Montserrat Light", 1, 14)); // NOI18N
        txtAddress.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(244, 158, 9), 2));
        jPanel2.add(txtAddress);
        txtAddress.setBounds(280, 500, 280, 30);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 280, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel1);
        jPanel1.setBounds(280, 150, 280, 380);

        comboRole.setFont(new java.awt.Font("Montserrat Light", 1, 14)); // NOI18N
        comboRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---" }));
        comboRole.setBorder(null);
        comboRole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboRoleActionPerformed(evt);
            }
        });
        jPanel2.add(comboRole);
        comboRole.setBounds(280, 540, 150, 40);

        background_updateEmployee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/FORMADJUSTED-03.png"))); // NOI18N
        jPanel2.add(background_updateEmployee);
        background_updateEmployee.setBounds(0, 0, 600, 690);

        btnUpdate.setText("UPDATE");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        jPanel2.add(btnUpdate);
        btnUpdate.setBounds(260, 600, 110, 30);

        btnClear.setText("CLEAR");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        jPanel2.add(btnClear);
        btnClear.setBounds(370, 600, 80, 30);

        btnCancel.setText("CANCEL");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        jPanel2.add(btnCancel);
        btnCancel.setBounds(460, 600, 100, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 690, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        uec.clear(this);
        //txtConfirm.setText("");
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        if(txtFirstname.getText().trim().equals("") || txtLastname.getText().trim().equals("") 
            || txtUsername.getText().trim().equals("") || txtPassword.getText().trim().equals("") 
            || txtConfirm.getText().trim().equals("") || txtEmail.getText().trim().equals("")
            || txtContactNumber.getText().trim().equals("") || txtAddress.getText().trim().equals("")
            || comboRole.getSelectedItem().equals("")) {
            JOptionPane.showMessageDialog(null, "Failed! Please fill up!");
        } else if (!txtPassword.getText().equals(txtConfirm.getText())) {
            JOptionPane.showMessageDialog(null, "Password doesn't match!");
        }else {
            if (JOptionPane.showConfirmDialog(null, "Are you sure you want to update this?", "Confirm Update",
                    JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                uec.update(this);
                PeoplePage peop = new PeoplePage(this.getName());
                peop.getLblUser().setText("Welcome, "+this.getName());
                peop.setVisible(true);             
                peop.setExtendedState(JFrame.MAXIMIZED_BOTH);
            }
            
        }
        
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        this.dispose();
        PeoplePage peop = new PeoplePage(this.getName());
        peop.getLblUser().setText("Welcome, "+this.getName());
        peop.setVisible(true);             
        peop.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }//GEN-LAST:event_btnCancelActionPerformed

    private void txtConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtConfirmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtConfirmActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void txtLastnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLastnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLastnameActionPerformed

    private void txtContactNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContactNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContactNumberActionPerformed

    private void comboRoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboRoleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboRoleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddEmp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddEmp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddEmp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddEmp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateEmp().setVisible(true);
            }
        });
    }
        
    public JTextField getTxtFirstname() {
        return txtFirstname;
    }

    public JTextField getTxtLastname() {
        return txtLastname;
    }

    public JPasswordField getTxtPassword() {
        return txtPassword;
    }
    
    public JPasswordField getTxtConfirm() {
        return txtConfirm;
    }

    public JTextField getTxtUsername() {
        return txtUsername;
    }
    
    public JTextField getTxtEmail(){
        return txtEmail;
    }
    
    public JTextField getTxtContactNumber(){
        return txtContactNumber;
    }
    
    public JTextField getTxtAddress(){
        return txtAddress;
    }
    
    public JComboBox getComboRole(){
        return comboRole;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background_updateEmployee;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> comboRole;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JPasswordField txtConfirm;
    private javax.swing.JTextField txtContactNumber;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFirstname;
    private javax.swing.JTextField txtLastname;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables

    Object getcomboRole() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
