/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cashierpage;

import adminpage.AdminPage;
import com.sun.glass.events.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import login.Login;
import models.ProductModel;
import models.SalesModel;
import models.TransactionModel;

/**
 *
 * @author Allysha
 */
public class CashierPage extends javax.swing.JFrame {

    /**
     * Creates new form CashierPage
     */
    CashierPageController cpc = new CashierPageController();
    
    private int id;
    private int isAdmin = 1;
    private Object[] row;
    JPanel panel;
    JFrame frame = new JFrame();
    
    public void setRow(Object[] row){
        this.row = row;
    }
    public Object[] getRow(){
        return row;
    }
    public int getIsAdmin(){
        return isAdmin;
    }
    
    public void setIsAdmin(int isAdmin){
        this.isAdmin = isAdmin;
    }
    public int getId(){
        return id;
    }
    public void setId(int id){
        this.id = id;
    }
    
    public CashierPage() {
        initComponents();
        tblCart.removeColumn(tblCart.getColumnModel().getColumn(0));
        btnUpdate.setEnabled(false);
        inputUpdate.setEnabled(false);
       
        this.setLocationRelativeTo(null);
    }
    
    public CashierPage(String name){
        initComponents();
        tblCart.removeColumn(tblCart.getColumnModel().getColumn(0));
        this.setLocationRelativeTo(null);
        setName(name);
       
        btnUpdate.setEnabled(false);
        inputUpdate.setEnabled(false);
       
        SalesModel salesm = new SalesModel();
    }
    public CashierPage(String name,int id){
        initComponents();
        
        tblCart.removeColumn(tblCart.getColumnModel().getColumn(0));
        this.setLocationRelativeTo(null);
        setName(name);
        setId(id);
        btnUpdate.setEnabled(false);
        inputUpdate.setEnabled(false);
       
        tblCart.getSelectionModel().addListSelectionListener(new ListSelectionListener(){
        
            public void valueChanged(ListSelectionEvent event) {
            SwingUtilities.invokeLater( 
                     new Runnable() {
                         public void run() {
                             btnUpdate.setEnabled(true);
                             inputUpdate.setEnabled(true);
                         }
                     }
                 );
            }
           });
        SalesModel salesm = new SalesModel();
    }
    
    public CashierPage(String name,int id, int isAdmin){
        initComponents();
        tblCart.removeColumn(tblCart.getColumnModel().getColumn(0));
        this.setLocationRelativeTo(null);
        setName(name);
        setId(id);
        setIsAdmin(isAdmin);
        btnUpdate.setEnabled(false);
        inputUpdate.setEnabled(false);
        if(this.getIsAdmin()==0){
        btnBack.setVisible(false);
        }
        SalesModel salesm = new SalesModel();
        
        tblCart.getSelectionModel().addListSelectionListener(new ListSelectionListener(){
        
            public void valueChanged(ListSelectionEvent event) {
            SwingUtilities.invokeLater( 
                     new Runnable() {
                         public void run() {
                             btnUpdate.setEnabled(true);
                             inputUpdate.setEnabled(true);
                         }
                     }
                 );
            }
           });
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jProgressBar1 = new javax.swing.JProgressBar();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jPanel4 = new javax.swing.JPanel();
        company = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        lblUser = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        inputProductCode = new javax.swing.JTextField();
        inputQty = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        btnRemove = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        inputUpdate = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCart = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        lblItems = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnCheckout = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        grandTotal = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        company.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        company.setText("Tanciong's General Merchandise");

        btnBack.setBackground(new java.awt.Color(204, 204, 255));
        btnBack.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnBack.setText("BACK");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblUser.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblUser.setText("jLabel2");

        btnLogout.setBackground(new java.awt.Color(204, 204, 255));
        btnLogout.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnLogout.setText("LOGOUT");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(248, 248, 248));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel1.setText("PRODUCT CODE:");

        inputProductCode.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        inputProductCode.setName(""); // NOI18N
        inputProductCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputProductCodeActionPerformed(evt);
            }
        });
        inputProductCode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                inputProductCodeKeyPressed(evt);
            }
        });

        inputQty.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        inputQty.setText("1");

        btnAdd.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnAdd.setText("ADD");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnRemove.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnRemove.setText("DELETE");
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });

        btnUpdate.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnUpdate.setText("UPDATE");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        inputUpdate.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        inputUpdate.setText("0");
        inputUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputUpdateActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel2.setText("UPDATE QUANTITY:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputProductCode, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputQty, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAdd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnUpdate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRemove)
                .addGap(15, 15, 15))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputProductCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdd)
                    .addComponent(inputQty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdate)
                    .addComponent(inputUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRemove))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        tblCart.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Item Name", "QTY", "Price", "Subtotal"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblCart);
        if (tblCart.getColumnModel().getColumnCount() > 0) {
            tblCart.getColumnModel().getColumn(0).setResizable(false);
        }

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        lblItems.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblItems.setText("0");

        jLabel8.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel8.setText("Item(s)");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblItems)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblItems)
                    .addComponent(jLabel8))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        btnCheckout.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnCheckout.setText("Checkout");
        btnCheckout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCheckout)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCheckout)
                .addGap(0, 8, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(250, 159, 66));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel3.setText("TOTAL:");

        grandTotal.setFont(new java.awt.Font("Tahoma", 0, 40)); // NOI18N
        grandTotal.setText("0.00");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(156, Short.MAX_VALUE)
                .addComponent(grandTotal)
                .addGap(152, 152, 152))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(2, 2, 2)
                .addComponent(grandTotal)
                .addContainerGap())
        );

        jPanel7.setBackground(new java.awt.Color(255, 165, 0));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(btnBack)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLogout))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(company)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblUser)))
                .addGap(30, 30, 30))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUser)
                    .addComponent(company))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLogout)
                    .addComponent(btnBack))
                .addGap(16, 16, 16)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        SalesModel sm = new SalesModel();
        TransactionModel tm = new TransactionModel();
        int res;
        float total;
        res =JOptionPane.showConfirmDialog(frame, "Are you sure do you want to log out?(Your Total Sales Will be Counted.)");
        if(res == JOptionPane.YES_OPTION){
            total = tm.computeTotalSales(getId());
            sm.addTotalSales(getId(), total);
            JOptionPane.showMessageDialog(frame,"You have Successfully logged out, your total sales is P"+total+"");
            Login l = new Login();
            l.setVisible(true);
             this.setVisible(false);
         
            this.dispose();
        }
        
        //EVERY TIME YOU LOG OUT, IT WILL CALCULATE THE TOTAL SALES WITHIN THE SHIFT
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        AdminPage ap = new AdminPage(this.getName(),this.getId());
        ap.getLblUser().setText("Welcome "+this.getName());
        ap.setVisible(true);
        
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void inputProductCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputProductCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputProductCodeActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
      try{  
        String name;
        int quantity, i,lblCount;
        long id;
        float price,subtotal,total;
        ProductModel pm = new ProductModel();
       
        DefaultTableModel model = (DefaultTableModel) tblCart.getModel();
        Object[] row = new Object[5];
        id = Long.parseLong(inputProductCode.getText());
        quantity = Integer.parseInt(inputQty.getText());
        ResultSet rs = pm.search(id);
        if(quantity > 0){
        if(Long.parseLong(inputProductCode.getText())>=0){
           
                row[0] = rs.getInt("product_id");
                row[1] = rs.getString("product_name");
                row[2] = quantity;
                row[3] = rs.getFloat("list_price");
                row[4] = quantity * rs.getFloat("list_price");
                //for(i=0 ; i<model.getRowCount() && !model.getValueAt(i, 0).equals(row[0]); i++){}
                model.addRow(row); 
                setRow(row);
                inputProductCode.setText("");
                inputQty.setText("1");
                
                if(Float.parseFloat(grandTotal.getText())==0){
                    grandTotal.setText(String.valueOf(row[4]));
                }else{
                    total = Float.parseFloat(grandTotal.getText());
                    grandTotal.setText(String.valueOf((Float)row[4]+total));
                    
                }
                
                if(Integer.parseInt(lblItems.getText())==0){
                    lblItems.setText(String.valueOf(1));
                    
                }else{
                    lblCount = Integer.parseInt(lblItems.getText());
                    lblItems.setText(String.valueOf(++lblCount));
                    
                }
            
        }
      }else{
             JOptionPane.showMessageDialog(frame, "Please Input a Valid Quantity");
        }
      }catch(SQLException em){
       
      }catch(NumberFormatException ez){
          JOptionPane.showMessageDialog(frame, "Please Input a Code(No Alphabetical Letters)");
      }
        
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        Object data = (Object)tblCart.getValueAt(tblCart.getSelectedRow(),0);
        int cartNdx=-1,lblCount;
        float newPrice;
        for(int row = 0 ; row < tblCart.getRowCount() ; row++){
            if(tblCart.getValueAt(row, 0).equals(data)){
                    cartNdx = row;
                }
            }
             
             newPrice = Float.parseFloat(grandTotal.getText()) - Float.parseFloat(String.valueOf(tblCart.getValueAt(cartNdx, 3)));
            ((DefaultTableModel)tblCart.getModel()).removeRow(cartNdx);
            grandTotal.setText(String.valueOf(newPrice));
            lblCount = Integer.parseInt(lblItems.getText());
            lblItems.setText(String.valueOf(--lblCount));
                    
        
    }//GEN-LAST:event_btnRemoveActionPerformed

    private void btnCheckoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckoutActionPerformed
        DefaultTableModel model = (DefaultTableModel) tblCart.getModel();
         
        if(Float.parseFloat(grandTotal.getText())!=0){
        ReceivePayment rp = new ReceivePayment(Float.parseFloat(grandTotal.getText()),getId(),getRow(),model.getRowCount(),model,grandTotal,lblItems);
       
       // rp.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        rp.setVisible(true);
        }else{
             JOptionPane.showMessageDialog(frame,"Please Create an Order First!");
        }
    }//GEN-LAST:event_btnCheckoutActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
          Object data = (Object)tblCart.getValueAt(tblCart.getSelectedRow(),0);
            int cartNdx=-1,lblCount,updateQty,qty;
            float total=0;
            updateQty = Integer.parseInt(inputUpdate.getText());
            float newPrice;
             for(int row = 0 ; row < tblCart.getRowCount() ; row++){
                if(tblCart.getValueAt(row, 0).equals(data)){
                    cartNdx = row;
                }
            }
           qty = Integer.parseInt(String.valueOf(tblCart.getValueAt(cartNdx,1)))-updateQty;
           System.out.println(Integer.parseInt(String.valueOf(tblCart.getValueAt(cartNdx, 1))));
            if(updateQty == 0 || updateQty == Integer.parseInt(String.valueOf(tblCart.getValueAt(cartNdx, 1)))){
               JOptionPane.showMessageDialog(frame, "There is No Need to Update!");
            }else{
                tblCart.setValueAt(updateQty, cartNdx, 1);
                newPrice =  Integer.parseInt(inputUpdate.getText())*Float.parseFloat(String.valueOf(tblCart.getValueAt(cartNdx, 2)));
                tblCart.setValueAt(newPrice,cartNdx,3);
                total = Float.parseFloat(grandTotal.getText()) - Float.parseFloat(String.valueOf(tblCart.getValueAt(cartNdx, 2)))*qty;
                grandTotal.setText(String.valueOf(total));
            }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void inputUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputUpdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputUpdateActionPerformed

    private void inputProductCodeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputProductCodeKeyPressed
         if(evt.getKeyCode()==KeyEvent.VK_ENTER){
          
           
             
             try{  
        String name;
        int quantity, i,lblCount;
        long id;
        float price,subtotal,total;
        ProductModel pm = new ProductModel();
       
        DefaultTableModel model = (DefaultTableModel) tblCart.getModel();
        Object[] row = new Object[5];
        id = Long.parseLong(inputProductCode.getText());
        quantity = Integer.parseInt(inputQty.getText());
        ResultSet rs = pm.search(id);
        if(quantity > 0){
        if(Long.parseLong(inputProductCode.getText())>=0){
           
                row[0] = rs.getInt("product_id");
                row[1] = rs.getString("product_name");
                row[2] = quantity;
                row[3] = rs.getFloat("list_price");
                row[4] = quantity * rs.getFloat("list_price");
                //for(i=0 ; i<model.getRowCount() && !model.getValueAt(i, 0).equals(row[0]); i++){}
                model.addRow(row); 
                setRow(row);
                inputProductCode.setText("");
                inputQty.setText("1");
                
                if(Float.parseFloat(grandTotal.getText())==0){
                    grandTotal.setText(String.valueOf(row[4]));
                }else{
                    total = Float.parseFloat(grandTotal.getText());
                    grandTotal.setText(String.valueOf((Float)row[4]+total));
                }
                
                if(Integer.parseInt(lblItems.getText())==0){
                    lblItems.setText(String.valueOf(1));
                    
                }else{
                    lblCount = Integer.parseInt(lblItems.getText());
                    lblItems.setText(String.valueOf(++lblCount));
                    
                }
            
        }
      }else{
             JOptionPane.showMessageDialog(frame, "Please Input a Valid Quantity");
             
        }
      }catch(SQLException em){
       
      }catch(NumberFormatException ez){
          JOptionPane.showMessageDialog(frame, "Please Input a Code(No Alphabetical Letters)");
          inputProductCode.setText("");
      }
             
        }
    }//GEN-LAST:event_inputProductCodeKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CashierPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CashierPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CashierPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CashierPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CashierPage().setVisible(true);
            }
        });
    }
    
    public JLabel getLblUser(){
        return lblUser;
    }
    
    public JLabel getGrandTotal(){
        return grandTotal;
    }
    
    public JTextField getInputProductCode(){
        return this.inputProductCode;
    }
    
    public JTextField getInputQty(){
        return inputQty;
    }
    
    public JTable getTblCart(){
        return tblCart;
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCheckout;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnRemove;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel company;
    private javax.swing.JLabel grandTotal;
    private javax.swing.JTextField inputProductCode;
    private javax.swing.JTextField inputQty;
    private javax.swing.JTextField inputUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblItems;
    private javax.swing.JLabel lblUser;
    private javax.swing.JTable tblCart;
    // End of variables declaration//GEN-END:variables

}
