/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package adminpage;

import cashierpage.CashierPage;
import cashierpage.ChangeFund;
import delivery.DeliveryPage;
import java.awt.Desktop;
import java.io.IOException;
import java.net.HttpURLConnection;
import java.net.MalformedURLException;
import java.net.ProtocolException;
import java.net.URI;
import java.net.URISyntaxException;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import login.Login;
import models.SalesModel;
import models.TransactionModel;
import peoplepage.PeoplePage;
import productpage.ProductPage;
import stockpage.StockPage;

/**
 *
 * @author Allysha
 */
public class AdminPage extends javax.swing.JFrame {

    /**
     * Creates new form AdminPage
     */
    //AdminPageController apc = new AdminPageController(); //calls adminpage controller
    
    /*
    private String name;
    
    public String getName(){
        return name;
    }
    
    public void setName(String name){
        this.name = name;
    }
    */
    private int id;
    JFrame frame = new JFrame();
    
    public AdminPage() {
        initComponents();
        this.setLocationRelativeTo(null);
        
    }
    
    public AdminPage(String name,int id) {
        initComponents();
        this.setLocationRelativeTo(null);
        setName(name);
        setId(id);
    }
    
      public AdminPage(String name) {
        initComponents();
        this.setLocationRelativeTo(null);
        setName(name);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblUser = new javax.swing.JLabel();
        background_admin = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();
        btnCashier = new javax.swing.JButton();
        btnProducts = new javax.swing.JButton();
        btnPeople = new javax.swing.JButton();
        btnReports = new javax.swing.JButton();
        btnDelivery = new javax.swing.JButton();
        btnStock = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 255, 255));
        jPanel1.setLayout(null);

        lblUser.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblUser.setText("jLabel1");
        jPanel1.add(lblUser);
        lblUser.setBounds(580, 10, 300, 20);

        background_admin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/THESIS TEMPLATE-02.png"))); // NOI18N
        jPanel1.add(background_admin);
        background_admin.setBounds(0, 0, 960, 560);

        btnLogout.setBackground(new java.awt.Color(204, 204, 255));
        btnLogout.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        jPanel1.add(btnLogout);
        btnLogout.setBounds(860, 10, 80, 70);

        btnCashier.setBackground(new java.awt.Color(255, 255, 255));
        btnCashier.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCashier.setText("CASHIER");
        btnCashier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCashierActionPerformed(evt);
            }
        });
        jPanel1.add(btnCashier);
        btnCashier.setBounds(160, 140, 130, 120);

        btnProducts.setBackground(new java.awt.Color(255, 255, 255));
        btnProducts.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnProducts.setText("PRODUCTS");
        btnProducts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductsActionPerformed(evt);
            }
        });
        jPanel1.add(btnProducts);
        btnProducts.setBounds(340, 140, 130, 120);

        btnPeople.setBackground(new java.awt.Color(255, 255, 255));
        btnPeople.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnPeople.setText("PEOPLE");
        btnPeople.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPeopleActionPerformed(evt);
            }
        });
        jPanel1.add(btnPeople);
        btnPeople.setBounds(520, 141, 120, 120);

        btnReports.setBackground(new java.awt.Color(255, 255, 255));
        btnReports.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnReports.setText("REPORTS");
        btnReports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportsActionPerformed(evt);
            }
        });
        jPanel1.add(btnReports);
        btnReports.setBounds(680, 131, 130, 130);

        btnDelivery.setBackground(new java.awt.Color(255, 255, 255));
        btnDelivery.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnDelivery.setText("DELIVERY");
        btnDelivery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeliveryActionPerformed(evt);
            }
        });
        jPanel1.add(btnDelivery);
        btnDelivery.setBounds(340, 299, 150, 100);

        btnStock.setBackground(new java.awt.Color(255, 255, 255));
        btnStock.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnStock.setText("STOCKS");
        btnStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStockActionPerformed(evt);
            }
        });
        jPanel1.add(btnStock);
        btnStock.setBounds(520, 290, 120, 110);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 961, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 561, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        SalesModel sm = new SalesModel();
        TransactionModel tm = new TransactionModel();
        int res;
        float total;
        res =JOptionPane.showConfirmDialog(frame, "Are you sure do you want to log out?(Your Total Sales Will be Counted.)");
        if(res == JOptionPane.YES_OPTION){
            total = tm.computeTotalSales(getId());
            sm.addTotalSales(getId(), total);
            JOptionPane.showMessageDialog(frame,"You have Successfully logged out, your total sales is P"+total+"");
            Login l = new Login();
            l.setVisible(true);
             this.setVisible(false);
         
            this.dispose();
        }
    }//GEN-LAST:event_btnLogoutActionPerformed
    public void logout(){
        SalesModel sm = new SalesModel();
        TransactionModel tm = new TransactionModel();
        int res;
        float total;
        res =JOptionPane.showConfirmDialog(frame, "Are you sure do you want to log out?(Your Total Sales Will be Counted.)");
        if(res == JOptionPane.YES_OPTION){
            total = tm.computeTotalSales(getId());
            sm.addTotalSales(getId(), total);
            JOptionPane.showMessageDialog(frame,"You have Successfully logged out, your total sales is P"+total+"");
            Login l = new Login();
            l.setVisible(true);
             this.setVisible(false);
         
            this.dispose();
        }
    }
    private void btnCashierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCashierActionPerformed
        SalesModel sm = new SalesModel();
        if(sm.checkDate()>=1){
            CashierPage cp = new CashierPage(this.getName(),this.getId());
                        cp.getLblUser().setText("Welcome, "+this.getName());
                        cp.setVisible(true);
                        cp.setExtendedState(JFrame.MAXIMIZED_BOTH);
                        this.dispose();
        }else{
        ChangeFund cf = new ChangeFund(this.getName(),this.getId()); //link the changefund and gets the name/username when logged in from the login
        cf.getLblUser().setText("Welcome, "+this.getName()); //displays the welcome message with the name/username

        cf.setVisible(true);
        this.dispose();
        
        //cf.setExtendedState(JFrame.MAXIMIZED_BOTH); 
        }
    }//GEN-LAST:event_btnCashierActionPerformed

    private void btnProductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductsActionPerformed
        ProductPage prp = new ProductPage(this.getName());
        prp.getLblUser().setText("Welcome, "+this.getName());
        
        prp.setVisible(true);
        this.dispose();
        
        prp.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }//GEN-LAST:event_btnProductsActionPerformed

    private void btnPeopleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPeopleActionPerformed
        PeoplePage peop = new PeoplePage(this.getName());
        peop.getLblUser().setText("Welcome, "+this.getName());
        
        peop.setVisible(true);
        this.dispose();
        
        peop.setExtendedState(JFrame.MAXIMIZED_BOTH); 
    }//GEN-LAST:event_btnPeopleActionPerformed

    private void btnDeliveryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeliveryActionPerformed
        DeliveryPage dp = new DeliveryPage(this.getName());
        dp.getLblUser().setText("Welcome, "+this.getName());
        
        dp.setVisible(true);
        this.dispose();
        
       dp.setExtendedState(JFrame.MAXIMIZED_BOTH); 
    }//GEN-LAST:event_btnDeliveryActionPerformed

    private void btnStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStockActionPerformed
       StockPage sp = new StockPage(this.getName());
       sp.getLblUser().setText("Welcome, "+this.getName());
       
       sp.setVisible(true);
       this.dispose();
       sp.setExtendedState(JFrame.MAXIMIZED_BOTH); 
    }//GEN-LAST:event_btnStockActionPerformed

    private void btnReportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportsActionPerformed
        Desktop browser = Desktop.getDesktop();
        try {
            browser.browse(new URI("http://localhost/Final_Tanciongs/REPORTS/"));
        } catch (IOException err){
        }
        catch(URISyntaxException err){
            
        }
    }//GEN-LAST:event_btnReportsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminPage().setVisible(true);
            }
        });
    }

    public JLabel getLblUser() {
        return lblUser;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background_admin;
    private javax.swing.JButton btnCashier;
    private javax.swing.JButton btnDelivery;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnPeople;
    private javax.swing.JButton btnProducts;
    private javax.swing.JButton btnReports;
    private javax.swing.JButton btnStock;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblUser;
    // End of variables declaration//GEN-END:variables

  public void setId(int id){
      this.id = id;
  }
  
  public int getId(){
      return id;
  }
}
